/** Named CR citations used by the host engine (not a compiler). */
export const CR = {
  corpAllottedClicks: { number: "1.11.2a", id: "rule_corp_allotted_clicks" },
  runnerAllottedClicks: { number: "1.11.2b", id: "rule_runner_allotted_clicks" },
  basicActions: { number: "5.2.3", id: "rule_basic_actions" },
  corpBasicCredit: { number: "5.2.6b", id: "rule_corp_basic_action_credit" },
  corpBasicDraw: { number: "5.2.6c", id: "rule_corp_basic_action_draw" },
  corpBasicInstall: { number: "5.2.6d", id: "rule_corp_basic_action_install" },
  runnerBasicCredit: { number: "5.2.7b", id: "runner_basic_action_credit" },
  runnerBasicDraw: { number: "5.2.7c", id: "runner_basic_action_card" },
  runnerBasicInstall: { number: "5.2.7d", id: "runner_basic_action_install" },
  runnerBasicRun: { number: "5.2.7f", id: "runner_basic_action_run" },
  actionPhase: { number: "5.4.1", id: "rule_action_phase_definition" },
  mandatoryDraw: { number: "5.3.2", id: "rule_mandatory_draw" },
  noRunnerDrawPhase: { number: "5.3.3", id: "rule_no_runner_draw_phase" },
  maxHandSize: { number: "5.5.3a", id: "rule_max_hand_size_default" },
  creatingRemotes: { number: "4.6.8b", id: "rule_creating_remote_servers" },
  remoteExistence: { number: "4.6.8d", id: "rule_remote_server_existence" },
  remoteCease: { number: "4.6.8e", id: "rule_remote_server_cease_to_exist" },
  announceServer: { number: "6.1.2a", id: "rule_announce_attacked_server" },
  successfulRun: { number: "6.7.2", id: "rule_successful_run" },
  breach: { number: "7.3.1", id: "rule_breaching_servers" },
  remoteCandidates: { number: "7.4.1a", id: "rule_candidates_in_server_root" },
  installing: { number: "8.5.1", id: "rule_installing" },
  corpInstallDest: { number: "8.5.2a", id: "rule_corp_install_choose_destination_server" },
  agendaAssetRemote: { number: "8.5.2b", id: "rule_agenda_asset_root_remote_server" },
  drawing: { number: "8.4.1", id: "rule_drawing" },
  gainCredits: { number: "1.10.3a", id: "rule_gain_credits" },
  spendClicks: { number: "1.11.3b", id: "rule_lose_spend_clicks" },
  rezInPaw: { number: "8.1.2a", id: "rule_rez_in_paw" },
  approachIce: { number: "6.4.1", id: "rule_approach_ice_phase" },
} as const;

export {
  CORP_STEPS,
  RUNNER_STEPS,
  RUN_STEPS,
  BREACH_STEPS,
  STEPS,
  START_STEP,
  cursorFrom,
} from "./graph.js";
