/** Named CR citations used by the host engine (not a compiler). */
export const CR = {
  corpAllottedClicks: { number: "1.11.2a", id: "rule_corp_allotted_clicks" },
  runnerAllottedClicks: { number: "1.11.2b", id: "rule_runner_allotted_clicks" },
  basicActions: { number: "5.2.3", id: "rule_basic_actions" },
  corpBasicCredit: { number: "5.2.6b", id: "rule_corp_basic_action_credit" },
  corpBasicDraw: { number: "5.2.6c", id: "rule_corp_basic_action_draw" },
  corpBasicInstall: { number: "5.2.6d", id: "rule_corp_basic_action_install" },
  runnerBasicCredit: { number: "5.2.7b", id: "runner_basic_action_credit" },
  runnerBasicDraw: { number: "5.2.7c", id: "runner_basic_action_card" },
  runnerBasicInstall: { number: "5.2.7d", id: "runner_basic_action_install" },
  runnerBasicRun: { number: "5.2.7f", id: "runner_basic_action_run" },
  actionPhase: { number: "5.4.1", id: "rule_action_phase_definition" },
  mandatoryDraw: { number: "5.3.2", id: "rule_mandatory_draw" },
  noRunnerDrawPhase: { number: "5.3.3", id: "rule_no_runner_draw_phase" },
  maxHandSize: { number: "5.5.3a", id: "rule_max_hand_size_default" },
  creatingRemotes: { number: "4.6.8b", id: "rule_creating_remote_servers" },
  remoteExistence: { number: "4.6.8d", id: "rule_remote_server_existence" },
  remoteCease: { number: "4.6.8e", id: "rule_remote_server_cease_to_exist" },
  announceServer: { number: "6.1.2a", id: "rule_announce_attacked_server" },
  successfulRun: { number: "6.7.2", id: "rule_successful_run" },
  breach: { number: "7.3.1", id: "rule_breaching_servers" },
  remoteCandidates: { number: "7.4.1a", id: "rule_candidates_in_server_root" },
  installing: { number: "8.5.1", id: "rule_installing" },
  corpInstallDest: { number: "8.5.2a", id: "rule_corp_install_choose_destination_server" },
  agendaAssetRemote: { number: "8.5.2b", id: "rule_agenda_asset_root_remote_server" },
  drawing: { number: "8.4.1", id: "rule_drawing" },
  gainCredits: { number: "1.10.3a", id: "rule_gain_credits" },
  spendClicks: { number: "1.11.3b", id: "rule_lose_spend_clicks" },
  rezInPaw: { number: "8.1.2a", id: "rule_rez_in_paw" },
  inherentRezCost: { number: "8.1.2d", id: "rule_inherent_rez_cost" },
  rezProcedure: { number: "8.1.2e", id: "rule_rez_procedure" },
  rezIceRestriction: { number: "6.4.3", id: "rule_rez_ice_restriction" },
  approachIce: { number: "6.4.1", id: "rule_approach_ice_phase" },
  encounterIce: { number: "6.5.1", id: "rule_encounter_ice_phase" },
  encounterBreakPaw: { number: "6.5.4", id: "rule_encounter_break_paw" },
  encounterSubResolve: { number: "6.5.5", id: "rule_encounter_sub_resolve" },
  fullyBreak: { number: "6.5.7a", id: "rule_fully_break" },
  endTheRun: { number: "6.1.4", id: "rule_end_the_run" },
  jackingOut: { number: "6.1.5", id: "rule_jacking_out" },
  jackOutAfterPass: { number: "6.1.5a", id: "rule_jack_out_after_passing_ice" },
  jackOutMovement: { number: "6.6.3", id: "rule_jack_out_movement_phase" },
  unsuccessfulRun: { number: "6.8.4", id: "rule_unsuccessful_run" },
  cannotPrecedence: { number: "1.2.2", id: "rule_cannot_precedence" },
  actionsOutsidePhase: { number: "5.2.4", id: "rule_actions_outside_action_phase" },
  costCheckpoint: { number: "1.16.3", id: "rule_cost_checkpoint" },
  timingCheckpoint: { number: "9.11.1b", id: "rule_checkpoint_timing_structure" },
  priority: { number: "9.2.3", id: "rule_priority" },
  priorityWindow: { number: "9.2.4", id: "rule_priority_window" },
  nestedPriorityWindow: { number: "9.2.4d", id: "rule_nested_priority_window" },
  paidAbility: { number: "9.5.1", id: "rule_paid_ability" },
  triggerPaidAbilities: { number: "9.5.2", id: "rule_trigger_paid_abilities" },
  icebreakerStrengthImplicit: {
    number: "3.9.5b",
    id: "rule_icebreaker_strength_increase_implicit",
  },
  icebreakerInterface: {
    number: "3.9.5f",
    id: "rule_icebreaker_interface_during_encounter",
  },
  icebreakerInterfaceStrength: {
    number: "3.9.5g",
    id: "rule_icebreaker_interface_strength",
  },
  programStrength: { number: "3.9.4a", id: "rule_icebreakers_strength_value" },
  iceStrength: { number: "3.4.4", id: "rule_ice_strength_value" },
  sufferDamage: { number: "10.4.1", id: "rule_suffer_or_take_damage" },
  netDamage: { number: "10.4.2a", id: "rule_meat_net_damage" },
  tags: { number: "10.5.1", id: "rule_tag" },
  tagged: { number: "10.5.2", id: "rule_tagged" },
  trashing: { number: "1.19.1", id: "rule_trashing" },
  scoringAgenda: { number: "1.17.6", id: "rule_agenda_scored" },
  stealingAgenda: { number: "1.17.7", id: "rule_agenda_stolen" },
  corpWinAgenda: { number: "1.7.2a", id: "rule_win_agenda_points" },
  runnerWinAgenda: { number: "1.7.2a", id: "rule_win_agenda_points" },
  flatline: { number: "1.7.2b", id: "rule_flatline" },
  brainDamage: { number: "10.4.2c", id: "rule_brain_damage" },
  meatDamage: { number: "10.4.2a", id: "rule_meat_net_damage" },
  preventDamage: { number: "9.9.5", id: "sec_prevent_avoid" },
  trace: { number: "10.8.1", id: "rule_trace_attempt_and_base_trace_strength" },
  recurringCredits: { number: "1.10.5a", id: "rule_recurring_credits" },
  advancing: { number: "1.18.1", id: "rule_advance" },
  corpBasicAdvance: { number: "5.2.6f", id: "corp_basic_action_advance" },
  playOperation: { number: "5.2.6e", id: "rule_corp_basic_action_operation" },
  playEvent: { number: "5.2.7e", id: "runner_basic_action_event" },
  hqAccess: { number: "7.4.1b", id: "rule_candidates_in_hq" },
  rdAccess: { number: "7.4.1c", id: "rule_candidates_in_rd" },
  archivesAccess: { number: "7.4.1d", id: "rule_candidates_in_archives" },
  identityAbility: { number: "9.1.1", id: "rule_ability" },
  midAccessAgenda: { number: "7.1.6", id: "rule_after_mid_access_agenda" },
} as const;


export {
  CORP_STEPS,
  RUNNER_STEPS,
  RUN_STEPS,
  BREACH_STEPS,
  STEPS,
  START_STEP,
  cursorFrom,
} from "./graph.js";
