/**
 * Effect IR kind names.
 *
 * A kind is snake_case and names the procedure: a verb, then the object.
 * `may_` means the player may decline. `corp_` or `runner_` may name the
 * actor before the verb. Pack codes and card titles are not prefixes.
 * Amounts, sides, and zones are fields.
 *
 * `_resolve`, `_pick`, and `_continue` are follow-ups the engine builds
 * while a choice is open. They are not the name of the printed ability.
 *
 * `LEGACY_PRIMITIVE_ALIASES` accepts a kind the cards pin v1.144.0 still
 * writes. Handlers use the procedure name. Drop an alias when a cards
 * release no longer contains the old kind.
 */

export const PACK_CODE_PREFIXES: ReadonlySet<string> = new Set([
  "au",
  "ber",
  "cotc",
  "dad",
  "dtwn",
  "ip",
  "ka",
  "kg",
  "mca",
  "mo",
  "o2",
  "oh",
  "si",
  "ss",
  "tdatd",
  "tlm",
  "uot",
  "win",
]);

/** First word of a procedure name, after optional may_ / corp_ / runner_. */
export const PROCEDURE_VERBS: ReadonlySet<string> = new Set([
  "access",
  "add",
  "advance",
  "arrange",
  "blank",
  "boost",
  "bottom",
  "brain",
  "break",
  "breach",
  "bypass",
  "charge",
  "choose",
  "copy",
  "core",
  "derez",
  "draw",
  "end",
  "expose",
  "fire",
  "flip",
  "forbid",
  "force",
  "forfeit",
  "fortify",
  "gain",
  "give",
  "grant",
  "host",
  "identify",
  "install",
  "jack",
  "look",
  "lose",
  "mark",
  "meat",
  "move",
  "name",
  "net",
  "offer",
  "pay",
  "pick",
  "place",
  "play",
  "prevent",
  "psi",
  "pump",
  "put",
  "redirect",
  "remove",
  "resolve",
  "return",
  "reveal",
  "rez",
  "rfg",
  "sabotage",
  "score",
  "search",
  "set",
  "shuffle",
  "spend",
  "steal",
  "suffer",
  "swap",
  "tag",
  "take",
  "top",
  "trace",
  "trash",
  "turn",
  "unless",
  "weaken",
]);

export const LEGACY_PRIMITIVE_ALIASES: Readonly<Record<string, string>> = {
  accelerated_beta_test_install_ice: "install_ice",
  accelerated_beta_test_trash_looked: "trash_looked",
  adept_break_sentry_or_barrier: "break_sentry_or_barrier",
  alexa_belsky_shuffle_hq: "shuffle_hq",
  alexa_belsky_shuffle_resolve: "shuffle_resolve",
  algernon_pay_gain_click: "pay_gain_click",
  analog_dreamers_shuffle_into_rd: "shuffle_into_rd",
  angel_arena_bottom_top: "bottom_top",
  angel_arena_place_x_counters: "place_x_counters",
  angel_arena_place_x_resolve: "place_x_resolve",
  angel_arena_reveal_top_may_bottom: "reveal_top_may_bottom",
  ankusa_add_fully_broken_barrier_to_hq: "add_fully_broken_barrier_to_hq",
  ark_lockdown_name_and_rfg_heap_copies: "name_and_rfg_heap_copies",
  ark_lockdown_rfg_named: "rfg_named",
  artist_colony_install_from_stack: "install_from_stack",
  artist_colony_search_stack_install: "search_stack_install",
  audacity_place_one_then_choose: "place_one_then_choose",
  audacity_trash_hq_place_total_2_advancements: "trash_hq_place_total_2_advancements",
  awakening_center_rez_hosted: "rez_hosted",
  back_channels_trash_remote_root: "trash_remote_root",
  bamboo_dome_choose_hq: "choose_hq",
  bamboo_dome_reveal_top_3: "reveal_top_3",
  bandwidth_give_tag_remove_if_successful: "give_tag_remove_if_successful",
  ber_host_on_ice: "host_on_ice",
  ber_rez_bioroid_and_host: "rez_bioroid_and_host",
  biased_reporting_choose_type: "choose_type",
  biased_reporting_corp_gain: "corp_gain",
  biased_reporting_runner_trash_continue: "runner_trash_continue",
  black_level_clearance_core_or_jack_out: "core_or_jack_out",
  black_level_clearance_jack_out: "jack_out",
  black_orchestra_spend_pump_and_break: "spend_pump_and_break",
  blackat_break_barrier: "break_barrier",
  bloo_moose_rfg_heap_gain_credits: "rfg_heap_gain_credits",
  bloo_moose_rfg_resolve: "rfg_resolve",
  bloodletter_trash_program_or_top_2_stack: "trash_program_or_top_2_stack",
  bloom_install_ice_inward: "install_ice_inward",
  bookmark_add_all_hosted_to_grip: "add_all_hosted_to_grip",
  bookmark_host_up_to_3_from_grip_facedown: "host_up_to_3_from_grip_facedown",
  brahman_add_nonvirus_program_to_stack_top: "add_nonvirus_program_to_stack_top",
  brahman_move_program_to_stack_top: "move_program_to_stack_top",
  broadcast_square_trace_prevent_bad_publicity: "trace_prevent_bad_publicity",
  brute_force_hack_derez_ice_rez_cost_lte_x: "derez_ice_rez_cost_lte_x",
  bryan_stinson_play_archives_transaction: "play_archives_transaction",
  bryan_stinson_play_archives_transaction_resolve: "play_archives_transaction_resolve",
  bug_may_pay_reveal_top: "may_pay_reveal_top",
  bug_out_bag_choose_x_and_load_power: "choose_x_and_load_power",
  bug_out_bag_draw_per_power_then_trash: "draw_per_power_then_trash",
  bug_reveal_top_paid: "reveal_top_paid",
  builder_move_to_outermost: "move_to_outermost",
  builder_move_to_server: "move_to_server",
  capstone_trash_grip_draw_for_installed_dupes: "trash_grip_draw_for_installed_dupes",
  careful_planning_choose_remote_card_cannot_rez_this_turn: "choose_remote_card_cannot_rez_this_turn",
  careful_planning_forbid_rez: "forbid_rez",
  casting_call_install_agenda_faceup: "install_agenda_faceup",
  charm_offensive_trash_rezzed_accessed: "trash_rezzed_accessed",
  clyde_van_rite_pay_or_trash_top_stack: "pay_or_trash_top_stack",
  code_siphon_install_program: "install_program",
  complete_image_name_net_damage_loop: "name_net_damage_loop",
  complete_image_net_named: "net_named",
  consulting_visit_play_resolve: "play_resolve",
  consulting_visit_search_rd_play_operation: "search_rd_play_operation",
  councilman_derez_resolve: "derez_resolve",
  councilman_may_derez_rezzed: "may_derez_rezzed",
  counter_surveillance_access_n: "access_n",
  customized_secretary_host_continue: "host_continue",
  customized_secretary_host_one: "host_one",
  customized_secretary_return_to_stack: "return_to_stack",
  customized_secretary_reveal_host_programs: "reveal_host_programs",
  cyber_threat_corp_rez: "corp_rez",
  daruma_swap_pick: "swap_pick",
  daruma_swap_this_root_with_other_root_or_hq: "swap_this_root_with_other_root_or_hq",
  data_folding_gain_if_unused_mu_gte: "gain_if_unused_mu_gte",
  data_hound_arrange_looked: "arrange_looked",
  davinci_install_from_grip_ignore_cost: "install_from_grip_ignore_cost",
  dean_lister_boost_icebreaker: "boost_icebreaker",
  defense_construct_add_facedown_archives_to_hq_per_advancement: "add_facedown_archives_to_hq_per_advancement",
  defense_construct_move_archives_to_hq: "move_archives_to_hq",
  defense_construct_pick_facedown_archives: "pick_facedown_archives",
  detente_host_random_hq: "host_random_hq",
  detente_return_two_hosted_may_access: "return_two_hosted_may_access",
  deuces_wild_expose_then_run: "expose_then_run",
  deuces_wild_resolve_two: "resolve_two",
  disposable_hq_add_hq_to_bottom_rd: "add_hq_to_bottom_rd",
  divested_trust_may_forfeit_return_stolen: "may_forfeit_return_stolen",
  dr_lovegood_blank_installed_abilities: "blank_installed_abilities",
  drive_by_expose_and_trash_remote_root: "expose_and_trash_remote_root",
  drive_by_expose_resolve: "expose_resolve",
  dummy_box_trash_grip_resolve: "trash_grip_resolve",
  dummy_box_trash_grip_same_type_prevent: "trash_grip_same_type_prevent",
  early_premiere_pay_place_advancement: "pay_place_advancement",
  eden_shard_install_instead: "install_instead",
  election_day_trash_hq_draw: "trash_hq_draw",
  equivocation_may_reveal_force_draw: "may_reveal_force_draw",
  equivocation_reveal_then_may_force_draw: "reveal_then_may_force_draw",
  estelle_moon_trash_per_power: "trash_per_power",
  eureka_reveal_install_or_trash: "reveal_install_or_trash",
  exchange_of_information_swap_resolve: "swap_resolve",
  exchange_of_information_swap_scored_agendas: "swap_scored_agendas",
  exploratory_romp_remove_up_to: "remove_up_to",
  expo_grid_gain_if_rezzed_asset_in_root: "gain_if_rezzed_asset_in_root",
  fall_guy_prevent_trash_resource: "prevent_trash_resource",
  false_echo_trash_then_corp_rez_or_hq: "trash_then_corp_rez_or_hq",
  fast_break_choose_remote: "choose_remote",
  fast_break_install_continue: "install_continue",
  fawkes_spend_x_pump: "spend_x_pump",
  fawkes_spend_x_pump_resolve: "spend_x_pump_resolve",
  fear_the_masses_reveal_copies_trash_rd: "reveal_copies_trash_rd",
  fenris_host_gmod_identity: "host_gmod_identity",
  fenris_host_gmod_identity_from_outside_game: "host_gmod_identity_from_outside_game",
  fester_corp_lose_two_if_can: "corp_lose_two_if_can",
  financial_collapse_lose_2_per_resource_or_trash: "lose_2_per_resource_or_trash",
  focus_group_may_pay_place: "may_pay_place",
  focus_group_reveal_may_advance: "reveal_may_advance",
  formicary_rez_move_innermost: "rez_move_innermost",
  frantic_coding_install_resolve: "install_resolve",
  frantic_coding_look_top_install: "look_top_install",
  gachapon_install_set_aside: "install_set_aside",
  gachapon_shuffle_pick_continue: "shuffle_pick_continue",
  gachapon_shuffle_selected_rfg_rest: "shuffle_selected_rfg_rest",
  game_over_trash_type_may_pay_3_prevent: "trash_type_may_pay_3_prevent",
  gemini_trace_subroutine: "trace_subroutine",
  gemini_trace_success: "trace_success",
  genetic_resequencing_add_counter: "add_counter",
  genetic_resequencing_place_agenda_counter: "place_agenda_counter",
  hades_shard_breach_archives: "breach_archives",
  hangeki_access_installed: "access_installed",
  hangeki_choose_installed_runner_may_access: "choose_installed_runner_may_access",
  harvester_draw_then_discard_down_to_hand_size: "draw_then_discard_down_to_hand_size",
  heartbeat_trash_installed_prevent_damage: "trash_installed_prevent_damage",
  hemorrhage_corp_trash_from_hq: "corp_trash_from_hq",
  herald_pay_place_advancements_resolve: "pay_place_advancements_resolve",
  herald_pay_up_to_place_advancements: "pay_up_to_place_advancements",
  holmegaard_forbid_access_and_breach_this_run: "forbid_access_and_breach_this_run",
  holmegaard_trash_installed_icebreaker: "trash_installed_icebreaker",
  howler_install_rez_bioroid_inward: "install_rez_bioroid_inward",
  howler_install_rez_chosen: "install_rez_chosen",
  ibrahim_salem_name_type_trash_from_grip: "name_type_trash_from_grip",
  ibrahim_salem_trash_named_type: "trash_named_type",
  ibrahim_salem_trash_resolve: "trash_resolve",
  immolation_script_trash_rezzed_copy: "trash_rezzed_copy",
  incubator_move_virus_counters: "move_virus_counters",
  independent_thinking_trash_draw: "trash_draw",
  information_overload_trash_per_tag: "trash_per_tag",
  information_sifting_access_pile: "access_pile",
  inject_reveal_top_four: "reveal_top_four",
  injection_attack_choose_breaker_run: "choose_breaker_run",
  invasion_of_privacy_trash_next: "trash_next",
  inversificator_may_swap_passed_ice: "may_swap_passed_ice",
  ip_enforcement_install_from_runner_score: "install_from_runner_score",
  it_department_boost_ice: "boost_ice",
  k_p_lynn_tag_or_end_the_run: "tag_or_end_the_run",
  keyhole_trash_looked_program: "trash_looked_program",
  kg_shuffle_archives_card_into_rd: "shuffle_archives_card_into_rd",
  kg_shuffle_one_archives_into_rd: "shuffle_one_archives_into_rd",
  khusyuk_access_set_aside: "access_set_aside",
  khusyuk_choose_install_cost_set_aside_access_shuffle: "choose_install_cost_set_aside_access_shuffle",
  khusyuk_set_aside_access_shuffle: "set_aside_access_shuffle",
  kitsune_breach_hq: "breach_hq",
  kitsune_breach_hq_resolve: "breach_hq_resolve",
  komainu_add_net_subs_for_rezzed_ice: "add_net_subs_for_rezzed_ice",
  liberated_chela_corp_forfeit_rfg: "corp_forfeit_rfg",
  liberated_chela_forfeit_resolve: "forfeit_resolve",
  liberated_chela_score_self: "score_self",
  liquidation_trash_any_rezzed_gain_3_each: "trash_any_rezzed_gain_3_each",
  liquidation_trash_rezzed_card: "trash_rezzed_card",
  localized_product_line_search_rd_copies_to_hq: "search_rd_copies_to_hq",
  localized_product_line_take_copies: "take_copies",
  loki_choose_rezzed_ice_gain_subs_subtypes_for_run: "choose_rezzed_ice_gain_subs_subtypes_for_run",
  loki_gain_from_ice: "gain_from_ice",
  london_library_add_hosted_program_to_grip: "add_hosted_program_to_grip",
  london_library_host_non_virus_program_ignore_cost: "host_non_virus_program_ignore_cost",
  london_library_host_program: "host_program",
  london_library_return_program: "return_program",
  long_term_investment_take_any_hosted_credits: "take_any_hosted_credits",
  loot_box_pick_revealed: "pick_revealed",
  loot_box_reveal_top_n: "reveal_top_n",
  mammon_spend_credits_place_power_counters: "spend_credits_place_power_counters",
  marker_add_etr_to_next_ice: "add_etr_to_next_ice",
  matryoshka_break_resolve: "break_resolve",
  maxwell_james_derez_remote_ice: "derez_remote_ice",
  maya_move_accessed_to_bottom_rd: "move_accessed_to_bottom_rd",
  mca_informant_host_on_connection: "host_on_connection",
  mca_informant_host_resolve: "host_resolve",
  media_blitz_gain_text_of_runner_scored_agenda: "gain_text_of_runner_scored_agenda",
  meeting_of_minds_reveal_gain: "reveal_gain",
  metamorph_swap_2_non_ice: "swap_2_non_ice",
  metamorph_swap_2_other_ice_or_2_non_ice: "swap_2_other_ice_or_2_non_ice",
  meteor_mining_may_gain_7_or_7_meat_if_tagged: "may_gain_7_or_7_meat_if_tagged",
  midori_may_swap_approached_ice_with_hq: "may_swap_approached_ice_with_hq",
  midori_swap_approached_ice_with_hq: "swap_approached_ice_with_hq",
  mind_game_psi_differ_redirect: "psi_differ_redirect",
  mind_game_redirect_resolve: "redirect_resolve",
  misdirection_spend_x_remove_tags: "spend_x_remove_tags",
  misdirection_spend_x_remove_tags_resolve: "spend_x_remove_tags_resolve",
  mumbad_city_hall_search_alliance_play_or_install: "search_alliance_play_or_install",
  muse_install_on_daemon: "install_on_daemon",
  muse_install_on_ice: "install_on_ice",
  muse_install_picked: "install_picked",
  muse_search_install_non_daemon: "search_install_non_daemon",
  muse_search_zone: "search_zone",
  mutate_trash_rezzed_ice_additional_cost: "trash_rezzed_ice_additional_cost",
  nasx_may_spend_to_place_power: "may_spend_to_place_power",
  nasx_spend_place_power_resolve: "spend_place_power_resolve",
  new_construction_install_from_hq_new_remote: "install_from_hq_new_remote",
  next_gold_trash_program_pick: "trash_program_pick",
  next_gold_trash_programs: "trash_programs",
  next_wave_2_may_core_if_rezzed_next_ice: "may_core_if_rezzed_next_ice",
  on_the_lam_prevent_tags_or_damage: "prevent_tags_or_damage",
  open_forum_reveal_top_rd_to_hq_then_hq_to_rd_top: "reveal_top_rd_to_hq_then_hq_to_rd_top",
  oracle_may_choose_type_reveal_install: "choose_type_reveal_install",
  oversight_ai_rez_and_host: "rez_and_host",
  pad_factory_place_advancement_cannot_score_until_next_turn: "place_advancement_cannot_score_until_next_turn",
  pad_factory_place_advancement_resolve: "place_advancement_resolve",
  paige_piper_search_stack_copies_to_heap: "search_stack_copies_to_heap",
  paintbrush_choose_ice_gain_subtype: "choose_ice_gain_subtype",
  panchatantra_choose_subtype_for_encounter: "choose_subtype_for_encounter",
  paperclip_spend_x_pump_and_break: "spend_x_pump_and_break",
  paperclip_spend_x_pump_and_break_resolve: "spend_x_pump_and_break_resolve",
  peeping_tom_choose_type_reveal_gain_etr_unless_tag_for_run: "choose_type_reveal_gain_etr_unless_tag_for_run",
  persephone_may_trash_stack_top_then_trash_rd_per_resolved: "may_trash_stack_top_then_trash_rd_per_resolved",
  persephone_resolve_trash: "resolve_trash",
  plan_b_reveal_score_from_hq: "reveal_score_from_hq",
  planned_assault_play_run_event_from_stack: "play_run_event_from_stack",
  plutus_may_play_transaction_from_archives: "may_play_transaction_from_archives",
  plutus_pay_rez_additional_cost: "pay_rez_additional_cost",
  political_dealings_install_agenda: "install_agenda",
  political_dealings_may_install_drawn_agenda: "may_install_drawn_agenda",
  political_graffiti_host_on_scored_agenda: "host_on_scored_agenda",
  political_operative_trash_rezzed_paying_trash_cost: "trash_rezzed_paying_trash_cost",
  power_nap_gain_per_double_in_heap: "gain_per_double_in_heap",
  power_shutdown_trash_rd: "trash_rd",
  power_shutdown_trash_runner_install_lte: "trash_runner_install_lte",
  product_recall_trash_rezzed_gain_trash_cost: "trash_rezzed_gain_trash_cost",
  psychokinesis_install_remote: "install_remote",
  psychokinesis_install_remote_resolve: "install_remote_resolve",
  psychokinesis_look_top5_may_install_remote: "look_top5_may_install_remote",
  psychokinesis_return_looked: "return_looked",
  pup_pay_or_net: "pay_or_net",
  quarantine_system_rez_continue: "rez_continue",
  quarantine_system_rez_one: "rez_one",
  quarantine_system_rez_up_to_3_ice_discount: "rez_up_to_3_ice_discount",
  queens_gambit_place_on: "place_on",
  queens_gambit_place_up_to: "place_up_to",
  raman_rai_may_swap_drawn: "may_swap_drawn",
  raymond_flint_breach_hq_no_root: "breach_hq_no_root",
  realloc_pick_second: "pick_second",
  recon_drone_prevent_x_damage: "prevent_x_damage",
  recon_drone_prevent_x_damage_resolve: "prevent_x_damage_resolve",
  red_planet_couriers_move_all_advancements: "move_all_advancements",
  reeducation_pick_continue: "pick_continue",
  replanting_add_installed_to_hq: "add_installed_to_hq",
  replanting_install_2_from_hq_ignore_costs: "install_2_from_hq_ignore_costs",
  replanting_install_from_hq_continue: "install_from_hq_continue",
  replanting_install_root_ignore_costs: "install_root_ignore_costs",
  replanting_move_to_hq: "move_to_hq",
  restore_install_rez_resolve: "install_rez_resolve",
  restoring_face_trash_exec_sysop_clone_remove_bp: "trash_exec_sysop_clone_remove_bp",
  reuse_spend_click_additional_cost: "spend_click_additional_cost",
  reuse_trash_hq_gain_credits: "trash_hq_gain_credits",
  reuse_trash_hq_gain_credits_finalize: "trash_hq_gain_credits_finalize",
  reuse_trash_hq_tick: "trash_hq_tick",
  rex_campaign_turn_begin: "turn_begin",
  rubicon_switch_derez_rezzed_this_turn: "derez_rezzed_this_turn",
  sacrifice_remove_bp_equal_forfeited_ap_gain_credits: "remove_bp_equal_forfeited_ap_gain_credits",
  sacrificial_clone_prevent_all_damage: "prevent_all_damage",
  sage_break_code_gate_or_barrier: "break_code_gate_or_barrier",
  salems_hospitality_name_reveal_trash_grip_copies: "name_reveal_trash_grip_copies",
  salems_hospitality_trash_named: "trash_named",
  savant_break_sentry_or_code_gates: "break_sentry_or_code_gates",
  savoir_faire_install_program_from_grip: "install_program_from_grip",
  sealed_vault_take_to_pool: "take_to_pool",
  security_chip_boost_breakers_per_link: "boost_breakers_per_link",
  security_nexus_trace_bypass_or_tag_etr: "trace_bypass_or_tag_etr",
  shoot_the_moon_rez_ice_per_tag: "rez_ice_per_tag",
  shoot_the_moon_rez_pick: "rez_pick",
  signal_jamming_forbid_installs_until_run_end: "forbid_installs_until_run_end",
  snatch_and_grab_offer_prevent: "offer_prevent",
  snatch_and_grab_prevent_with_tag: "prevent_with_tag",
  snatch_and_grab_trash_connection: "trash_connection",
  special_report_draw_shuffled: "draw_shuffled",
  special_report_shuffle_any_hq_draw: "shuffle_any_hq_draw",
  special_report_shuffle_hq_card: "shuffle_hq_card",
  spot_the_prey_expose_non_ice_then_run: "expose_non_ice_then_run",
  spy_camera_look_top_x_stack_arrange: "look_top_x_stack_arrange",
  standoff_corp_trash: "corp_trash",
  standoff_trash_loop: "trash_loop",
  street_peddler_install_hosted: "install_hosted",
  subcontract_play_op_resolve: "play_op_resolve",
  subcontract_play_ops_from_hq: "play_ops_from_hq",
  success_advance_equal_forfeit_advancement_requirement: "advance_equal_forfeit_advancement_requirement",
  surfer_swap_encounter_barrier_adjacent: "swap_encounter_barrier_adjacent",
  tapwrm_gain_credits_per_corp_credits: "gain_credits_per_corp_credits",
  targeted_marketing_name_card: "name_card",
  targeted_marketing_set_name: "set_name",
  tech_startup_install_asset: "install_asset",
  tech_startup_search_rd_asset_install: "search_rd_asset_install",
  the_shadow_net_play_event_from_heap: "play_event_from_heap",
  toshiyuki_sakai_swap_execute: "swap_execute",
  toshiyuki_sakai_swap_with_hq: "swap_with_hq",
  touch_ups_choose_type_shuffle_grip: "choose_type_shuffle_grip",
  touch_ups_shuffle_grip_of_type: "shuffle_grip_of_type",
  trade_in_add_hw_to_grip: "add_hw_to_grip",
  trade_in_trash_hardware_additional_cost: "trash_hardware_additional_cost",
  transparency_initiative_host_on_agenda: "host_on_agenda",
  turntable_swap_stolen_with_corp_scored: "swap_stolen_with_corp_scored",
  unleash_rez_ice_then_may_resolve_sub: "rez_ice_then_may_resolve_sub",
  unleash_rez_may_resolve_sub: "rez_may_resolve_sub",
  vigil_draw_if_hq_full: "draw_if_hq_full",
  virus_breeding_ground_move_counter: "move_counter",
  waiver_reveal_grip_trash_cost_lte_excess: "reveal_grip_trash_cost_lte_excess",
  wall_to_wall_place_adv_on_ice: "place_adv_on_ice",
  wall_to_wall_turn_begin_continue: "turn_begin_continue",
  weir_trash_one_from_grip: "trash_one_from_grip",
  whistleblower_may_trash_name_agenda_steal_ignore_costs: "may_trash_name_agenda_steal_ignore_costs",
  whistleblower_name_agenda: "name_agenda",
  windfall_shuffle_trash_top_gain_install_cost: "shuffle_trash_top_gain_install_cost",
  worlds_plaza_install_asset_from_hq_rez_discount: "install_asset_from_hq_rez_discount",
};

export function canonicalPrimitiveKind(kind: string): string {
  return LEGACY_PRIMITIVE_ALIASES[kind] ?? kind;
}

export function primitiveNameFollowsStandard(kind: string): boolean {
  if (!/^[a-z][a-z0-9]*(_[a-z0-9]+)*$/.test(kind)) return false;
  const lead = kind.split("_")[0]!;
  if (PACK_CODE_PREFIXES.has(lead)) return false;
  let parts = kind.split("_");
  if (parts[0] === "may") parts = parts.slice(1);
  if (parts[0] === "corp" || parts[0] === "runner") parts = parts.slice(1);
  const verb = parts[0];
  return verb !== undefined && PROCEDURE_VERBS.has(verb);
}
